export const PUBLIC_SHOPIFY_DOMAIN = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN ?? "";
export const PUBLIC_SHOPIFY_TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN ?? "";
export const STOREFRONT_API_VERSION = "2026-04";

export const IS_SHOPIFY_PUBLIC_READY = Boolean(PUBLIC_SHOPIFY_DOMAIN && PUBLIC_SHOPIFY_TOKEN);
